using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGeneratorExample;

public static class RepositoryMarker
{
    public const string MarkerNamespace = "SourceGeneratorExample";
    public const string MarkerInterfaceName = "IRepository";
    public const string MarkerFullyQualifiedName = $"{MarkerNamespace}.{MarkerInterfaceName}";
    private static string Source => 
        $$"""
          // <auto-generated/>
          namespace {{MarkerNamespace}} {
              public interface {{MarkerInterfaceName}} { }
          }
          """;
    
    public static void GenerateModelMarker(this IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            $"{MarkerFullyQualifiedName}.g.cs",
            SourceText.From(Source, Encoding.UTF8)));
    }
}